### ISSUE TITLE
Issues with ray build

### ISSUE THREAD

**Issue by kfordaccela** [andyrew/piHDR#3]
having issues with "sudo ./makeall install" currently, it's not doing something correctly with current rPi install, trying to find issue and will report back.

**Comment by kfordaccela** [comment]
Doing some research the following command was needed to fix

"X11/Xlib.h"

```sudo apt install libx11-dev```

Article Used: https://stackoverflow.com/questions/5299989/x11-xlib-h-not-found-in-ubuntu

**Comment by kfordaccela** [comment]
Errors with "Ray" build resolved.

**Comment by andyrew** [comment]
Installing libx11-dev is in the readme documentation, just before the wget command.
Andy

**Comment by kfordaccela** [comment]
Please note that this was already in the documentation and didn't run for some reason.

**Comment by Bra1nsen** [comment]
![Screenshot 2022-03-25 101124](https://user-images.githubusercontent.com/58213050/160093375-7b7f2875-bfed-448f-8124-05bbc73ed684.png)
 any idea ?
